# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-23 19:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelance',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 7, 23, 19, 54, 46, 615073)),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 7, 23, 19, 54, 46, 616656)),
        ),
        migrations.AlterField(
            model_name='user_data_form',
            name='data_input',
            field=models.CharField(max_length=10),
        ),
    ]
