# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-28 12:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_data', '0004_auto_20170728_0540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data_form',
            name='number_of_count',
        ),
        migrations.AlterField(
            model_name='freelance',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 7, 28, 12, 3, 35, 645138)),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 7, 28, 12, 3, 35, 647053)),
        ),
    ]
