# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-28 12:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_data', '0005_auto_20170728_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data_form',
            name='data_input',
        ),
        migrations.AlterField(
            model_name='freelance',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 7, 28, 12, 23, 55, 602092)),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 7, 28, 12, 23, 55, 603310)),
        ),
    ]
