# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-28 13:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_data', '0006_auto_20170728_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data_form',
            name='data_input',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='freelance',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 7, 28, 13, 16, 26, 493271)),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 7, 28, 13, 16, 26, 494663)),
        ),
    ]
