# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-06 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_data', '0009_test2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelance',
            name='average',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='freelance',
            name='max_salary',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='freelance',
            name='min_salary',
            field=models.IntegerField(),
        ),
    ]
