# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-07 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_data', '0010_auto_20170806_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='title2',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
